// {
// "status": "ok",
// "totalResults": 62,
// "articles": [
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "الجزيرة نت",
// "title": "\"نمو ما بعد الصدمة\".. كيف تجعلك المِحن شخصا أفضل؟ - الجزيرة نت",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMi3AFodHRwczovL3d3dy5hbGphemVlcmEubmV0L2xpZmVzdHlsZS8yMDIzLzUvMjkvJUQ5JTg2JUQ5JTg1JUQ5JTg4LSVEOSU4NSVEOCVBNy0lRDglQTglRDglQjklRDglQUYtJUQ4JUE3JUQ5JTg0JUQ4JUI1JUQ4JUFGJUQ5JTg1JUQ4JUE5LSVEOSU4MyVEOSU4QSVEOSU4MS0lRDglQUElRDglQUMlRDglQjklRDklODQlRDklODMtJUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ5JTkwJUQ4JUFEJUQ5JTg20gHgAWh0dHBzOi8vd3d3LmFsamF6ZWVyYS5uZXQvYW1wL2xpZmVzdHlsZS8yMDIzLzUvMjkvJUQ5JTg2JUQ5JTg1JUQ5JTg4LSVEOSU4NSVEOCVBNy0lRDglQTglRDglQjklRDglQUYtJUQ4JUE3JUQ5JTg0JUQ4JUI1JUQ4JUFGJUQ5JTg1JUQ4JUE5LSVEOSU4MyVEOSU4QSVEOSU4MS0lRDglQUElRDglQUMlRDglQjklRDklODQlRDklODMtJUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ5JTkwJUQ4JUFEJUQ5JTg2?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T19:55:53Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "CNN Arabic",
// "title": "رصدها تلسكوب عملاق.. شاهد بقعة هائلة على سطح الشمس أكبر من حجم كوكب الأرض - CNN Arabic",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMia2h0dHBzOi8vYXJhYmljLmNubi5jb20vbWlzY2VsbGFuZW91cy92aWRlby8yMDIzLzA1LzI5L3YxMzg3MjItc3VuLXNvbGFyLW1heGltdW0tamFuZXQtaXZleS1jbm50bXctY3Byb2ctdnB40gFzaHR0cHM6Ly9hcmFiaWMuY25uLmNvbS9hbXBodG1sL21pc2NlbGxhbmVvdXMvdmlkZW8vMjAyMy8wNS8yOS92MTM4NzIyLXN1bi1zb2xhci1tYXhpbXVtLWphbmV0LWl2ZXktY25udG13LWNwcm9nLXZweA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T19:48:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "نسمة لايف",
// "title": "مصابة بالتوحد وتحصّلت على الماجستير.. من هي الطفلة الأعلى ذكاء من أينشتاين؟ - نسمة لايف",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMi3QNodHRwczovL3d3dy5uZXNzbWEudHYvYXIvJUQ4JUEzJUQ4JUFFJUQ4JUE4JUQ4JUE3JUQ4JUIxLSVEOCVCOSVEOCVBNyVEOSU4NCVEOSU4NSVEOSU4QSVEOCVBOS9hY3R1LyVEOSU4NSVEOCVCNSVEOCVBNyVEOCVBOCVEOCVBOS0lRDglQTglRDglQTclRDklODQlRDglQUElRDklODglRDglQUQlRDglQUYtJUQ5JTg4JUQ4JUFBJUQ4JUFEJUQ4JUI1LSVEOSU4NCVEOCVBQS0lRDglQjklRDklODQlRDklODktJUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ4JUE3JUQ4JUFDJUQ4JUIzJUQ4JUFBJUQ5JThBJUQ4JUIxLSVEOSU4NSVEOSU4Ni0lRDklODclRDklOEEtJUQ4JUE3JUQ5JTg0JUQ4JUI3JUQ5JTgxJUQ5JTg0JUQ4JUE5LSVEOCVBNyVEOSU4NCVEOCVBMyVEOCVCOSVEOSU4NCVEOSU4OS0lRDglQjAlRDklODMlRDglQTclRDglQTEtJUQ5JTg1JUQ5JTg2LSVEOCVBMyVEOSU4QSVEOSU4NiVEOCVCNCVEOCVBQSVEOCVBNyVEOSU4QSVEOSU4Ni80NTQwMznSAeEDaHR0cHM6Ly93d3cubmVzc21hLnR2L2FyL2FtcC8lRDglQTMlRDglQUUlRDglQTglRDglQTclRDglQjEtJUQ4JUI5JUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ5JThBJUQ4JUE5L2FjdHUvJUQ5JTg1JUQ4JUI1JUQ4JUE3JUQ4JUE4JUQ4JUE5LSVEOCVBOCVEOCVBNyVEOSU4NCVEOCVBQSVEOSU4OCVEOCVBRCVEOCVBRi0lRDklODglRDglQUElRDglQUQlRDglQjUtJUQ5JTg0JUQ4JUFBLSVEOCVCOSVEOSU4NCVEOSU4OS0lRDglQTclRDklODQlRDklODUlRDglQTclRDglQUMlRDglQjMlRDglQUElRDklOEElRDglQjEtJUQ5JTg1JUQ5JTg2LSVEOSU4NyVEOSU4QS0lRDglQTclRDklODQlRDglQjclRDklODElRDklODQlRDglQTktJUQ4JUE3JUQ5JTg0JUQ4JUEzJUQ4JUI5JUQ5JTg0JUQ5JTg5LSVEOCVCMCVEOSU4MyVEOCVBNyVEOCVBMS0lRDklODUlRDklODYtJUQ4JUEzJUQ5JThBJUQ5JTg2JUQ4JUI0JUQ4JUFBJUQ4JUE3JUQ5JThBJUQ5JTg2LzQ1NDAzOQ?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T18:51:14Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "صحيفة الشرق الأوسط",
// "title": "تحديد جينات أوروبية في مومياء مصرية بآيرلندا - صحيفة الشرق الأوسط",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMiyQJodHRwczovL2Fhd3NhdC5jb20vJUQ5JThBJUQ5JTg4JUQ5JTg1JUQ5JThBJUQ4JUE3JUQ4JUFBLSVEOCVBNyVEOSU4NCVEOCVCNCVEOCVCMSVEOSU4Mi80MzU0MjExLSVEOCVBQSVEOCVBRCVEOCVBRiVEOSU4QSVEOCVBRi0lRDglQUMlRDklOEElRDklODYlRDglQTclRDglQUEtJUQ4JUEzJUQ5JTg4JUQ4JUIxJUQ5JTg4JUQ4JUE4JUQ5JThBJUQ4JUE5LSVEOSU4MSVEOSU4QS0lRDklODUlRDklODglRDklODUlRDklOEElRDglQTclRDglQTEtJUQ5JTg1JUQ4JUI1JUQ4JUIxJUQ5JThBJUQ4JUE5LSVEOCVBOCVEOCVBMiVEOSU4QSVEOCVCMSVEOSU4NCVEOSU4NiVEOCVBRiVEOCVBN9IBAA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T18:45:02Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "اليوم السابع",
// "title": "كيمياء لغات.. مراجعة هامة لأبرز النقاط التي يجب التركيز عليها قبل الامتحانات - اليوم السابع",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMi4wJodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyMy81LzI5LyVEOSU4MyVEOSU4QSVEOSU4NSVEOSU4QSVEOCVBNyVEOCVBMS0lRDklODQlRDglQkElRDglQTclRDglQUEtJUQ5JTg1JUQ4JUIxJUQ4JUE3JUQ4JUFDJUQ4JUI5JUQ4JUE5LSVEOSU4NyVEOCVBNyVEOSU4NSVEOCVBOS0lRDklODQlRDglQTMlRDglQTglRDglQjElRDglQjItJUQ4JUE3JUQ5JTg0JUQ5JTg2JUQ5JTgyJUQ4JUE3JUQ4JUI3LSVEOCVBNyVEOSU4NCVEOCVBQSVEOSU4QS0lRDklOEElRDglQUMlRDglQTgtJUQ4JUE3JUQ5JTg0JUQ4JUFBJUQ4JUIxJUQ5JTgzJUQ5JThBJUQ4JUIyLSVEOCVCOSVEOSU4NCVEOSU4QSVEOSU4NyVEOCVBNy82MTk1ODU00gHfAmh0dHBzOi8vbS55b3VtNy5jb20vYW1wLzIwMjMvNS8yOS8lRDklODMlRDklOEElRDklODUlRDklOEElRDglQTclRDglQTEtJUQ5JTg0JUQ4JUJBJUQ4JUE3JUQ4JUFBLSVEOSU4NSVEOCVCMSVEOCVBNyVEOCVBQyVEOCVCOSVEOCVBOS0lRDklODclRDglQTclRDklODUlRDglQTktJUQ5JTg0JUQ4JUEzJUQ4JUE4JUQ4JUIxJUQ4JUIyLSVEOCVBNyVEOSU4NCVEOSU4NiVEOSU4MiVEOCVBNyVEOCVCNy0lRDglQTclRDklODQlRDglQUElRDklOEEtJUQ5JThBJUQ4JUFDJUQ4JUE4LSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVCMSVEOSU4MyVEOSU4QSVEOCVCMi0lRDglQjklRDklODQlRDklOEElRDklODclRDglQTcvNjE5NTg1NA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T18:00:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "الجزيرة نت",
// "title": "يهدد الأمن الغذائي والتنوع الحيوي.. توقعات بتقلص أعداد المزارع عالميا إلى النصف بحلول 2100 - الجزيرة نت",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMi3gFodHRwczovL3d3dy5hbGphemVlcmEubmV0L3NjaWVuY2UvMjAyMy81LzI5LyVEOSU4QSVEOSU4NyVEOCVBRiVEOCVBRi0lRDglQTclRDklODQlRDglQTMlRDklODUlRDklODYtJUQ4JUE3JUQ5JTg0JUQ4JUJBJUQ4JUIwJUQ4JUE3JUQ4JUE2JUQ5JThBLSVEOSU4OCVEOCVBNyVEOSU4NCVEOCVBQSVEOSU4NiVEOSU4OCVEOCVCOS0lRDglQTclRDklODQlRDglQUQlRDklOEElRDklODglRDklOEHSAeIBaHR0cHM6Ly93d3cuYWxqYXplZXJhLm5ldC9hbXAvc2NpZW5jZS8yMDIzLzUvMjkvJUQ5JThBJUQ5JTg3JUQ4JUFGJUQ4JUFGLSVEOCVBNyVEOSU4NCVEOCVBMyVEOSU4NSVEOSU4Ni0lRDglQTclRDklODQlRDglQkElRDglQjAlRDglQTclRDglQTYlRDklOEEtJUQ5JTg4JUQ4JUE3JUQ5JTg0JUQ4JUFBJUQ5JTg2JUQ5JTg4JUQ4JUI5LSVEOCVBNyVEOSU4NCVEOCVBRCVEOSU4QSVEOSU4OCVEOSU4QQ?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T15:04:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "العربية",
// "title": "كيف يقضي علي القرني وريانة برناوي يومهما في الفضاء؟ - العربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMivwJodHRwczovL3d3dy5hbGFyYWJpeWEubmV0L2FsYXJhYml5YS10b2RheS8yMDIzLzA1LzI5LyVEOSU4MyVEOSU4QSVEOSU4MS0lRDklOEElRDklODIlRDglQjYlRDklOEEtJUQ4JUI5JUQ5JTg0JUQ5JThBLSVEOCVBNyVEOSU4NCVEOSU4MiVEOCVCMSVEOSU4NiVEOSU4QS0lRDklODglRDglQjElRDklOEElRDglQTclRDklODYlRDglQTktJUQ4JUE4JUQ4JUIxJUQ5JTg2JUQ4JUE3JUQ5JTg4JUQ5JThBLSVEOSU4QSVEOSU4OCVEOSU4NSVEOSU4NyVEOSU4NSVEOCVBNy0lRDklODElRDklOEEtJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ4JUI2JUQ4JUE3JUQ4JUExJUQ4JTlG0gHDAmh0dHBzOi8vd3d3LmFsYXJhYml5YS5uZXQvYW1wL2FsYXJhYml5YS10b2RheS8yMDIzLzA1LzI5LyVEOSU4MyVEOSU4QSVEOSU4MS0lRDklOEElRDklODIlRDglQjYlRDklOEEtJUQ4JUI5JUQ5JTg0JUQ5JThBLSVEOCVBNyVEOSU4NCVEOSU4MiVEOCVCMSVEOSU4NiVEOSU4QS0lRDklODglRDglQjElRDklOEElRDglQTclRDklODYlRDglQTktJUQ4JUE4JUQ4JUIxJUQ5JTg2JUQ4JUE3JUQ5JTg4JUQ5JThBLSVEOSU4QSVEOSU4OCVEOSU4NSVEOSU4NyVEOSU4NSVEOCVBNy0lRDklODElRDklOEEtJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ4JUI2JUQ4JUE3JUQ4JUExJUQ4JTlG?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T15:01:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "العربية",
// "title": "تقرير طبي يجيب عن سؤال: ماذا يحدث للإنسان بعد الموت؟ - العربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMiuAJodHRwczovL3d3dy5hbGFyYWJpeWEubmV0L3NjaWVuY2UvMjAyMy8wNS8yOS8lRDglQUElRDklODIlRDglQjElRDklOEElRDglQjEtJUQ4JUI3JUQ4JUE4JUQ5JThBLSVEOSU4QSVEOCVBQyVEOSU4QSVEOCVBOC0lRDglQjklRDklODQlRDklODktJUQ4JUIzJUQ4JUE0JUQ4JUE3JUQ5JTg0LSVEOSU4NSVEOCVBNyVEOCVCMCVEOCVBNy0lRDklOEElRDglQUQlRDglQUYlRDglQUItJUQ5JTg0JUQ5JTg0JUQ4JUE3JUQ5JTg2JUQ4JUIzJUQ4JUE3JUQ5JTg2LSVEOCVBOCVEOCVCOSVEOCVBRi0lRDglQTclRDklODQlRDklODUlRDklODglRDglQUElRDglOUbSAbwCaHR0cHM6Ly93d3cuYWxhcmFiaXlhLm5ldC9hbXAvc2NpZW5jZS8yMDIzLzA1LzI5LyVEOCVBQSVEOSU4MiVEOCVCMSVEOSU4QSVEOCVCMS0lRDglQjclRDglQTglRDklOEEtJUQ5JThBJUQ4JUFDJUQ5JThBJUQ4JUE4LSVEOCVCOSVEOSU4NCVEOSU4OS0lRDglQjMlRDglQTQlRDglQTclRDklODQtJUQ5JTg1JUQ4JUE3JUQ4JUIwJUQ4JUE3LSVEOSU4QSVEOCVBRCVEOCVBRiVEOCVBQi0lRDklODQlRDklODQlRDglQTclRDklODYlRDglQjMlRDglQTclRDklODYtJUQ4JUE4JUQ4JUI5JUQ4JUFGLSVEOCVBNyVEOSU4NCVEOSU4NSVEOSU4OCVEOCVBQSVEOCU5Rg?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T13:06:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "Sky News Arabia سكاي نيوز عربية",
// "title": "منذ 100 عام.. شنغهاي تسجل أكثر أيام شهر مايو حرا - Sky News Arabia سكاي نيوز عربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMi4wFodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS90ZWNobm9sb2d5LzE2MjQ5MTItMTAwLSVEOCVCOSVEOCVBNyVEOSU4NS0lRDglQjQlRDklODYlRDglQkElRDklODclRDglQTclRDklOEEtJUQ4JUFBJUQ4JUIzJUQ4JUFDJUQ5JTg0LSVEOCVBNyVEOSU5NCVEOSU4QSVEOCVBNyVEOSU4NS0lRDglQjQlRDklODclRDglQjEtJUQ5JTg1JUQ4JUE3JUQ5JThBJUQ5JTg4LSVEOCVBRCVEOCVCMSVEOCVBN9IB5wFodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS9hbXAvdGVjaG5vbG9neS8xNjI0OTEyLTEwMC0lRDglQjklRDglQTclRDklODUtJUQ4JUI0JUQ5JTg2JUQ4JUJBJUQ5JTg3JUQ4JUE3JUQ5JThBLSVEOCVBQSVEOCVCMyVEOCVBQyVEOSU4NC0lRDglQTclRDklOTQlRDklOEElRDglQTclRDklODUtJUQ4JUI0JUQ5JTg3JUQ4JUIxLSVEOSU4NSVEOCVBNyVEOSU4QSVEOSU4OC0lRDglQUQlRDglQjElRDglQTc?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T11:07:15Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "Sky News Arabia سكاي نيوز عربية",
// "title": "أسلاف الأفيال.. اكتشاف مقبرة لحيوانات انقرضت من 5 ملايين سنة - Sky News Arabia سكاي نيوز عربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMi2gJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS90ZWNobm9sb2d5LzE2MjQ5MDMtJUQ4JUE3JUQ5JTk0JUQ4JUIzJUQ5JTg0JUQ4JUE3JUQ5JTgxLSVEOCVBNyVEOSU4NCVEOCVBNyVEOSU5NCVEOSU4MSVEOSU4QSVEOCVBNyVEOSU4NC0lRDglQTclRDklODMlRDglQUElRDglQjQlRDglQTclRDklODEtJUQ5JTg1JUQ5JTgyJUQ4JUE4JUQ4JUIxJUQ4JUE5LSVEOSU4NCVEOCVBRCVEOSU4QSVEOSU4OCVEOCVBNyVEOSU4NiVEOCVBNyVEOCVBQS0lRDglQTclRDklODYlRDklODIlRDglQjElRDglQjYlRDglQUEtNS0lRDklODUlRDklODQlRDglQTclRDklOEElRDklOEElRDklODYtJUQ4JUIzJUQ5JTg2JUQ4JUE50gHeAmh0dHBzOi8vd3d3LnNreW5ld3NhcmFiaWEuY29tL2FtcC90ZWNobm9sb2d5LzE2MjQ5MDMtJUQ4JUE3JUQ5JTk0JUQ4JUIzJUQ5JTg0JUQ4JUE3JUQ5JTgxLSVEOCVBNyVEOSU4NCVEOCVBNyVEOSU5NCVEOSU4MSVEOSU4QSVEOCVBNyVEOSU4NC0lRDglQTclRDklODMlRDglQUElRDglQjQlRDglQTclRDklODEtJUQ5JTg1JUQ5JTgyJUQ4JUE4JUQ4JUIxJUQ4JUE5LSVEOSU4NCVEOCVBRCVEOSU4QSVEOSU4OCVEOCVBNyVEOSU4NiVEOCVBNyVEOCVBQS0lRDglQTclRDklODYlRDklODIlRDglQjElRDglQjYlRDglQUEtNS0lRDklODUlRDklODQlRDglQTclRDklOEElRDklOEElRDklODYtJUQ4JUIzJUQ5JTg2JUQ4JUE5?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T10:33:13Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "Sky News Arabia سكاي نيوز عربية",
// "title": "الإمارات تعلن تفاصيل مشروع استكشاف \"حزام الكويكبات\" - Sky News Arabia سكاي نيوز عربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMivwJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS90ZWNobm9sb2d5LzE2MjQ4OTYtJUQ4JUE3JUQ5JTg0JUQ4JUE3JUQ5JTk1JUQ5JTg1JUQ4JUE3JUQ4JUIxJUQ4JUE3JUQ4JUFBLSVEOCVBQSVEOCVCOSVEOSU4NCVEOSU4Ni0lRDglQUElRDklODElRDglQTclRDglQjUlRDklOEElRDklODQtJUQ5JTg1JUQ4JUI0JUQ4JUIxJUQ5JTg4JUQ4JUI5LSVEOCVBNyVEOCVCMyVEOCVBQSVEOSU4MyVEOCVCNCVEOCVBNyVEOSU4MS0lRDglQUQlRDglQjIlRDglQTclRDklODUtJUQ4JUE3JUQ5JTg0JUQ5JTgzJUQ5JTg4JUQ5JThBJUQ5JTgzJUQ4JUE4JUQ4JUE3JUQ4JUFB0gHDAmh0dHBzOi8vd3d3LnNreW5ld3NhcmFiaWEuY29tL2FtcC90ZWNobm9sb2d5LzE2MjQ4OTYtJUQ4JUE3JUQ5JTg0JUQ4JUE3JUQ5JTk1JUQ5JTg1JUQ4JUE3JUQ4JUIxJUQ4JUE3JUQ4JUFBLSVEOCVBQSVEOCVCOSVEOSU4NCVEOSU4Ni0lRDglQUElRDklODElRDglQTclRDglQjUlRDklOEElRDklODQtJUQ5JTg1JUQ4JUI0JUQ4JUIxJUQ5JTg4JUQ4JUI5LSVEOCVBNyVEOCVCMyVEOCVBQSVEOSU4MyVEOCVCNCVEOCVBNyVEOSU4MS0lRDglQUQlRDglQjIlRDglQTclRDklODUtJUQ4JUE3JUQ5JTg0JUQ5JTgzJUQ5JTg4JUQ5JThBJUQ5JTgzJUQ4JUE4JUQ4JUE3JUQ4JUFB?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T10:16:08Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "اليوم السابع",
// "title": "آخر ظاهرة فلكية خلال مايو.. عطارد فى أقصى استطالة له اليوم والزهرة مع نجم بولوكس - اليوم السابع",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMirQJodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyMy81LzI5LyVEOCVBMiVEOCVBRSVEOCVCMS0lRDglQjglRDglQTclRDklODclRDglQjElRDglQTktJUQ5JTgxJUQ5JTg0JUQ5JTgzJUQ5JThBJUQ4JUE5LSVEOCVBRSVEOSU4NCVEOCVBNyVEOSU4NC0lRDklODUlRDglQTclRDklOEElRDklODgtJUQ4JUI5JUQ4JUI3JUQ4JUE3JUQ4JUIxJUQ4JUFGLSVEOSU4MSVEOSU4OS0lRDglQTMlRDklODIlRDglQjUlRDklODktJUQ4JUE3JUQ4JUIzJUQ4JUFBJUQ4JUI3JUQ4JUE3JUQ5JTg0JUQ4JUE5LSVEOSU4NCVEOSU4Ny82MTk1Nzky0gGpAmh0dHBzOi8vbS55b3VtNy5jb20vYW1wLzIwMjMvNS8yOS8lRDglQTIlRDglQUUlRDglQjEtJUQ4JUI4JUQ4JUE3JUQ5JTg3JUQ4JUIxJUQ4JUE5LSVEOSU4MSVEOSU4NCVEOSU4MyVEOSU4QSVEOCVBOS0lRDglQUUlRDklODQlRDglQTclRDklODQtJUQ5JTg1JUQ4JUE3JUQ5JThBJUQ5JTg4LSVEOCVCOSVEOCVCNyVEOCVBNyVEOCVCMSVEOCVBRi0lRDklODElRDklODktJUQ4JUEzJUQ5JTgyJUQ4JUI1JUQ5JTg5LSVEOCVBNyVEOCVCMyVEOCVBQSVEOCVCNyVEOCVBNyVEOSU4NCVEOCVBOS0lRDklODQlRDklODcvNjE5NTc5Mg?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T09:05:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "طقس العرب",
// "title": "الأردن | سُحب رعدية تترافق بأمطار غزيرة تشهدها العديد من مناطق البادية - طقس العرب",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMijwNodHRwczovL3d3dy5hcmFiaWF3ZWF0aGVyLmNvbS9hci9jb250ZW50LyVEOCVBNyVEOSU4NCVEOCVBMyVEOCVCMSVEOCVBRiVEOSU4Ni0lRDglQjMlRDklOEYlRDglQUQlRDglQTgtJUQ4JUIxJUQ4JUI5JUQ4JUFGJUQ5JThBJUQ4JUE5LSVEOCVBQSVEOCVBQSVEOCVCMSVEOCVBNyVEOSU4MSVEOSU4Mi0lRDglQTglRDglQTMlRDklODUlRDglQjclRDglQTclRDglQjEtJUQ4JUJBJUQ4JUIyJUQ5JThBJUQ4JUIxJUQ4JUE5LSVEOCVBQSVEOCVCNCVEOSU4NyVEOCVBRiVEOSU4NyVEOCVBNy0lRDglQTclRDklODQlRDglQjklRDglQUYlRDklOEElRDglQUYtJUQ5JTg1JUQ5JTg2LSVEOSU4NSVEOSU4NiVEOCVBNyVEOCVCNyVEOSU4Mi0lRDglQTclRDklODQlRDglQTglRDglQTclRDglQUYlRDklOEElRDglQTnSAZMDaHR0cHM6Ly93d3cuYXJhYmlhd2VhdGhlci5jb20vYXIvYW1wL2NvbnRlbnQvJUQ4JUE3JUQ5JTg0JUQ4JUEzJUQ4JUIxJUQ4JUFGJUQ5JTg2LSVEOCVCMyVEOSU4RiVEOCVBRCVEOCVBOC0lRDglQjElRDglQjklRDglQUYlRDklOEElRDglQTktJUQ4JUFBJUQ4JUFBJUQ4JUIxJUQ4JUE3JUQ5JTgxJUQ5JTgyLSVEOCVBOCVEOCVBMyVEOSU4NSVEOCVCNyVEOCVBNyVEOCVCMS0lRDglQkElRDglQjIlRDklOEElRDglQjElRDglQTktJUQ4JUFBJUQ4JUI0JUQ5JTg3JUQ4JUFGJUQ5JTg3JUQ4JUE3LSVEOCVBNyVEOSU4NCVEOCVCOSVEOCVBRiVEOSU4QSVEOCVBRi0lRDklODUlRDklODYtJUQ5JTg1JUQ5JTg2JUQ4JUE3JUQ4JUI3JUQ5JTgyLSVEOCVBNyVEOSU4NCVEOCVBOCVEOCVBNyVEOCVBRiVEOSU4QSVEOCVBOQ?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T08:56:27Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "Al Masry Al Youm - المصري اليوم",
// "title": "«كل في فلك يسبحون».. التربيع الأول لـ«قمر ذي القعدة» 1444 هجرية يزين سماء مصر (صور) - Al Masry Al Youm - المصري اليوم",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMiMmh0dHBzOi8vd3d3LmFsbWFzcnlhbHlvdW0uY29tL25ld3MvZGV0YWlscy8yODk3ODUy0gEA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T08:48:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "اليوم السابع",
// "title": "المنظمة العالمية للأرصاد الجوية: توقعات بارتفاع درجات الحرارة لمستويات قياسية - اليوم السابع",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMiyQNodHRwczovL3d3dy55b3VtNy5jb20vc3RvcnkvMjAyMy81LzI5LyVEOCVBNyVEOSU4NCVEOSU4NSVEOSU4NiVEOCVCOCVEOSU4NSVEOCVBOS0lRDglQTclRDklODQlRDglQjklRDglQTclRDklODQlRDklODUlRDklOEElRDglQTktJUQ5JTg0JUQ5JTg0JUQ4JUEzJUQ4JUIxJUQ4JUI1JUQ4JUE3JUQ4JUFGLSVEOCVBNyVEOSU4NCVEOCVBQyVEOSU4OCVEOSU4QSVEOCVBOS0lRDglQUElRDklODglRDklODIlRDglQjklRDglQTclRDglQUEtJUQ4JUE4JUQ4JUE3JUQ4JUIxJUQ4JUFBJUQ5JTgxJUQ4JUE3JUQ4JUI5LSVEOCVBRiVEOCVCMSVEOCVBQyVEOCVBNyVEOCVBQS0lRDglQTclRDklODQlRDglQUQlRDglQjElRDglQTclRDglQjElRDglQTktJUQ5JTg0JUQ5JTg1JUQ4JUIzJUQ4JUFBJUQ5JTg4JUQ5JThBJUQ4JUE3JUQ4JUFBLSVEOSU4MiVEOSU4QSVEOCVBNyVEOCVCMyVEOSU4QSVEOCVBOS82MTk1Njcz0gHFA2h0dHBzOi8vbS55b3VtNy5jb20vYW1wLzIwMjMvNS8yOS8lRDglQTclRDklODQlRDklODUlRDklODYlRDglQjglRDklODUlRDglQTktJUQ4JUE3JUQ5JTg0JUQ4JUI5JUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ5JThBJUQ4JUE5LSVEOSU4NCVEOSU4NCVEOCVBMyVEOCVCMSVEOCVCNSVEOCVBNyVEOCVBRi0lRDglQTclRDklODQlRDglQUMlRDklODglRDklOEElRDglQTktJUQ4JUFBJUQ5JTg4JUQ5JTgyJUQ4JUI5JUQ4JUE3JUQ4JUFBLSVEOCVBOCVEOCVBNyVEOCVCMSVEOCVBQSVEOSU4MSVEOCVBNyVEOCVCOS0lRDglQUYlRDglQjElRDglQUMlRDglQTclRDglQUEtJUQ4JUE3JUQ5JTg0JUQ4JUFEJUQ4JUIxJUQ4JUE3JUQ4JUIxJUQ4JUE5LSVEOSU4NCVEOSU4NSVEOCVCMyVEOCVBQSVEOSU4OCVEOSU4QSVEOCVBNyVEOCVBQS0lRDklODIlRDklOEElRDglQTclRDglQjMlRDklOEElRDglQTkvNjE5NTY3Mw?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T07:51:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "العربية",
// "title": "الصين سترسل الثلاثاء أول رائد مدني إلى الفضاء - العربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMimAJodHRwczovL3d3dy5hbGFyYWJpeWEubmV0L3NjaWVuY2UvMjAyMy8wNS8yOS8lRDglQTclRDklODQlRDglQjUlRDklOEElRDklODYtJUQ4JUIzJUQ4JUFBJUQ4JUIxJUQ4JUIzJUQ5JTg0LSVEOCVBNyVEOSU4NCVEOCVBQiVEOSU4NCVEOCVBNyVEOCVBQiVEOCVBNyVEOCVBMS0lRDglQTMlRDklODglRDklODQtJUQ4JUIxJUQ4JUE3JUQ4JUE2JUQ4JUFGLSVEOSU4NSVEOCVBRiVEOSU4NiVEOSU4QS0lRDglQTclRDklODQlRDklODktJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ4JUI2JUQ4JUE3JUQ4JUEx0gGcAmh0dHBzOi8vd3d3LmFsYXJhYml5YS5uZXQvYW1wL3NjaWVuY2UvMjAyMy8wNS8yOS8lRDglQTclRDklODQlRDglQjUlRDklOEElRDklODYtJUQ4JUIzJUQ4JUFBJUQ4JUIxJUQ4JUIzJUQ5JTg0LSVEOCVBNyVEOSU4NCVEOCVBQiVEOSU4NCVEOCVBNyVEOCVBQiVEOCVBNyVEOCVBMS0lRDglQTMlRDklODglRDklODQtJUQ4JUIxJUQ4JUE3JUQ4JUE2JUQ4JUFGLSVEOSU4NSVEOCVBRiVEOSU4NiVEOSU4QS0lRDglQTclRDklODQlRDklODktJUQ4JUE3JUQ5JTg0JUQ5JTgxJUQ4JUI2JUQ4JUE3JUQ4JUEx?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T07:33:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "الحرة",
// "title": "\"دراسة كبرى\" تكشف السر.. كيف يعزز التحفيز الكهربائي وظائف عقلك؟ - الحرة",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMizAJodHRwczovL3d3dy5hbGh1cnJhLmNvbS9oZWFsdGgvMjAyMy8wNS8yOS8lRDglQUYlRDglQjElRDglQTclRDglQjMlRDglQTktJUQ5JTgzJUQ4JUE4JUQ4JUIxJUQ5JTg5LSVEOCVBQSVEOSU4MyVEOCVCNCVEOSU4MS0lRDglQTclRDklODQlRDglQjMlRDglQjEtJUQ5JThBJUQ4JUI5JUQ4JUIyJUQ4JUIyLSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVBRCVEOSU4MSVEOSU4QSVEOCVCMi0lRDglQTclRDklODQlRDklODMlRDklODclRDglQjElRDglQTglRDglQTclRDglQTYlRDklOEEtJUQ5JTg4JUQ4JUI4JUQ4JUE3JUQ4JUE2JUQ5JTgxLSVEOCVCOSVEOSU4MiVEOSU4NCVEOSU4MyVEOCU5RtIB0AJodHRwczovL3d3dy5hbGh1cnJhLmNvbS9oZWFsdGgvMjAyMy8wNS8yOS8lRDglQUYlRDglQjElRDglQTclRDglQjMlRDglQTktJUQ5JTgzJUQ4JUE4JUQ4JUIxJUQ5JTg5LSVEOCVBQSVEOSU4MyVEOCVCNCVEOSU4MS0lRDglQTclRDklODQlRDglQjMlRDglQjEtJUQ5JThBJUQ4JUI5JUQ4JUIyJUQ4JUIyLSVEOCVBNyVEOSU4NCVEOCVBQSVEOCVBRCVEOSU4MSVEOSU4QSVEOCVCMi0lRDglQTclRDklODQlRDklODMlRDklODclRDglQjElRDglQTglRDglQTclRDglQTYlRDklOEEtJUQ5JTg4JUQ4JUI4JUQ4JUE3JUQ4JUE2JUQ5JTgxLSVEOCVCOSVEOSU4MiVEOSU4NCVEOSU4MyVEOCU5Rj9hbXA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T07:02:38Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "Al Masry Al Youm - المصري اليوم",
// "title": "بمشاركة ثماني دول عربية.. افتتاح الدورة التدريبية «العربية للطاقة الذرية» في مجال معجل السيكلوترون - Al Masry Al Youm - المصري اليوم",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMiMmh0dHBzOi8vd3d3LmFsbWFzcnlhbHlvdW0uY29tL25ld3MvZGV0YWlscy8yODk3ODI10gEA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T06:01:00Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "Sky News Arabia سكاي نيوز عربية",
// "title": "بالفيديو.. اختفاء ظل الكعبة المشرفة خلال ظاهرة فلكية فريدة - Sky News Arabia سكاي نيوز عربية",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMivwJodHRwczovL3d3dy5za3luZXdzYXJhYmlhLmNvbS92YXJpZXRpZXMvMTYyNDgxNS0lRDglQTglRDglQTclRDklODQlRDklODElRDklOEElRDglQUYlRDklOEElRDklODgtJUQ4JUE3JUQ4JUFFJUQ4JUFBJUQ5JTgxJUQ4JUE3JUQ4JUExLSVEOCVCOCVEOSU4NC0lRDglQTclRDklODQlRDklODMlRDglQjklRDglQTglRDglQTktJUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ4JUI0JUQ4JUIxJUQ5JTgxJUQ4JUE5LSVEOCVCOCVEOCVBNyVEOSU4NyVEOCVCMSVEOCVBOS0lRDklODElRDklODQlRDklODMlRDklOEElRDglQTktJUQ5JTgxJUQ4JUIxJUQ5JThBJUQ4JUFGJUQ4JUE50gHDAmh0dHBzOi8vd3d3LnNreW5ld3NhcmFiaWEuY29tL2FtcC92YXJpZXRpZXMvMTYyNDgxNS0lRDglQTglRDglQTclRDklODQlRDklODElRDklOEElRDglQUYlRDklOEElRDklODgtJUQ4JUE3JUQ4JUFFJUQ4JUFBJUQ5JTgxJUQ4JUE3JUQ4JUExLSVEOCVCOCVEOSU4NC0lRDglQTclRDklODQlRDklODMlRDglQjklRDglQTglRDglQTktJUQ4JUE3JUQ5JTg0JUQ5JTg1JUQ4JUI0JUQ4JUIxJUQ5JTgxJUQ4JUE5LSVEOCVCOCVEOCVBNyVEOSU4NyVEOCVCMSVEOCVBOS0lRDklODElRDklODQlRDklODMlRDklOEElRDglQTktJUQ5JTgxJUQ4JUIxJUQ5JThBJUQ4JUFGJUQ4JUE5?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T04:45:37Z",
// "content": null
// },
// {
// "source": {
// "id": "google-news",
// "name": "Google News"
// },
// "author": "الحرة",
// "title": "\"يخفي النجوم ويسبب السمنة\".. علماء يحذرون من \"التلوث الضوئي\" - الحرة",
// "description": null,
// "url": "https://news.google.com/rss/articles/CBMitwJodHRwczovL3d3dy5hbGh1cnJhLmNvbS90ZWNoLzIwMjMvMDUvMjkvJUQ5JThBJUQ4JUFFJUQ5JTgxJUQ5JThBLSVEOCVBNyVEOSU4NCVEOSU4NiVEOCVBQyVEOSU4OCVEOSU4NS0lRDklODglRDklOEElRDglQjMlRDglQTglRDglQTgtJUQ4JUE3JUQ5JTg0JUQ4JUIzJUQ5JTg1JUQ5JTg2JUQ4JUE5LSVEOCVCOSVEOSU4NCVEOSU4NSVEOCVBNyVEOCVBMS0lRDklOEElRDglQUQlRDglQjAlRDglQjElRDklODglRDklODYtJUQ4JUE3JUQ5JTg0JUQ4JUFBJUQ5JTg0JUQ5JTg4JUQ4JUFCLSVEOCVBNyVEOSU4NCVEOCVCNiVEOSU4OCVEOCVBNiVEOSU4QdIBuwJodHRwczovL3d3dy5hbGh1cnJhLmNvbS90ZWNoLzIwMjMvMDUvMjkvJUQ5JThBJUQ4JUFFJUQ5JTgxJUQ5JThBLSVEOCVBNyVEOSU4NCVEOSU4NiVEOCVBQyVEOSU4OCVEOSU4NS0lRDklODglRDklOEElRDglQjMlRDglQTglRDglQTgtJUQ4JUE3JUQ5JTg0JUQ4JUIzJUQ5JTg1JUQ5JTg2JUQ4JUE5LSVEOCVCOSVEOSU4NCVEOSU4NSVEOCVBNyVEOCVBMS0lRDklOEElRDglQUQlRDglQjAlRDglQjElRDklODglRDklODYtJUQ4JUE3JUQ5JTg0JUQ4JUFBJUQ5JTg0JUQ5JTg4JUQ4JUFCLSVEOCVBNyVEOSU4NCVEOCVCNiVEOSU4OCVEOCVBNiVEOSU4QT9hbXA?oc=5",
// "urlToImage": null,
// "publishedAt": "2023-05-29T03:26:59Z",
// "content": null
// }
// ]
// }